# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TP3_Comparateur_Couche
                                 A QGIS plugin
 Ce plugin sert a comparer deux couches entre elles.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-22
        copyright            : (C) 2025 by Raphael Sourceaux; Jeremy Gagnon
        email                : wadwada@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TP3_Comparateur_Couche class from file TP3_Comparateur_Couche.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TP3_Comparateur_Couche import TP3_Comparateur_Couche
    return TP3_Comparateur_Couche(iface)
